### ISSUE TITLE
Running locally, script needs to assert JDK v17 minimum

### ISSUE THREAD

**Issue by seefood** [n0k0m3/revanced-build-template#12]
https://github.com/n0k0m3/revanced-build-template/blob/0863230567019ae4e78913867c14b3c018cfe031/build_revanced.sh#L69

check jkava --version and warn the user if JDK is too old.
on my home Ubuntu, for instance, I had to upgrade to JDK17 and the headless version is not enough, it looks for AWT so it needs the full JDK.

if you want me to fork and PR, I can do it too, and fix up a pre-commit config on the way. LMK.

**Comment by n0k0m3** [comment]
Feel free to make a PR

**Comment by seefood** [comment]
made PR #21
