### ISSUE TITLE
download APK

### ISSUE THREAD

**Issue by antifarben** [n0k0m3/revanced-build-template#14]
It would be nice if the official YT apk could be directly downloaded (i.e. via [one of these download scripts](https://github.com/search?l=Python&q=download+apk&type=Repositories)).

**Comment by n0k0m3** [comment]
Not to be condescending, but leaving a search URL for a simple query "download apk" doesn't help the situation. If you have a script that can download from APKMirror and get specific bundled APK (not apkm) version then feel free to make a PR, otherwise this won't be implemented

**Comment by antifarben** [comment]
> If you have a script that can download from APKMirror

If I may ask: why only APKMirror ([1](https://github.com/Sebby37/youtube-vanced-apkmirror-scraper), [2](https://github.com/mkg20001/apkmirror-client)) and not Google Play Store ([1](https://github.com/bluemutedwisdom/google-play-downloader/blob/master/gplay-downloader.py), [2](https://github.com/ClaudiuGeorgiu/PlaystoreDownloader#-demo), [3](https://github.com/HamidrezaMoradi/APK-Downloader)), [Aptoide](https://github.com/StefanescuCristian/Aptoide-Downloader) or [AppsApk](https://github.com/goorax/appsapk_downloader)?

**Comment by n0k0m3** [comment]
Note: both APKMirror scripts mentioned used scrapping and won't work reliably bc Cloudflare rate limiting (sometimes build VM got rate limited from CF)
Aptoide and AppsApk doesn't have latest APK
