### ISSUE TITLE
Play Protect shows warning.

### ISSUE THREAD

**Issue by ronin08** [n0k0m3/revanced-build-template#2]
I had installed many revanced builds, none of them showed this prompt. Is it signed properly? 
![IMG_20220616_021847](https://user-images.githubusercontent.com/75478274/173924878-d05a1326-fe73-488a-a584-f87cfa2632ed.jpg)

**Comment by n0k0m3** [comment]
Those are either signed by Google signed certs/keystore or the android-sdk default `testkey` which is 10 years old. The ReVanced-CLI used their own key to sign the APK so that's why you got the error

**Comment by n0k0m3** [comment]
Closed due to no reply
