### ISSUE TITLE
Why only uploading root revanced apks ??

### ISSUE THREAD

**Issue by AmirulAndalib** [n0k0m3/revanced-build-template#26]
![Screenshot_20220706-210746](https://user-images.githubusercontent.com/86344856/177583193-d8354662-138a-433f-ab43-8cd519f09f3f.png)

**Comment by n0k0m3** [comment]
Can't reproduce, can you run the action again?

**Comment by n0k0m3** [comment]
I'll close this as there hasn't been any reply for a while, feel free to reopen if the issue persists
