### ISSUE TITLE
Excluded Patches are applying anyways

### ISSUE THREAD

**Issue by kevindeoz** [n0k0m3/revanced-build-template#29]
I edited my `patches.txt` file to exclude some patches but they are applying as shown on the workflow log
Its something wrong with my file or the script?
I tried both, Build and Experimental

![imagen](https://user-images.githubusercontent.com/67438842/178167536-d486f6f8-30b6-4f1a-8e90-82d371477e9d.png)

![imagen](https://user-images.githubusercontent.com/67438842/178167551-37046346-b2c2-42b0-bd19-8f9a7edead13.png)

![imagen](https://user-images.githubusercontent.com/67438842/178167627-3f8fcd64-85b0-4699-8f3c-5b409cf9a3df.png)

**Comment by ManorSailor** [comment]
Fixed in #30. Please wait for it to merge & then fetch upstream, alternatively, you can add the fix yourself or cherry pick it from my forked repo

**Comment by n0k0m3** [comment]
Fixed thanks a lot @kevindeoz for reporting and @ManorSailor for fixing
