### ISSUE TITLE
Getting some warnings while the app is being built

### ISSUE THREAD

**Issue by gosndka** [n0k0m3/revanced-build-template#35]
WARNING: Skipping music-video-ads: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music 
WARNING: Skipping exclusive-audio-playback: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music 
WARNING: Skipping codecs-unlock: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music 
WARNING: Skipping background-play: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music 
WARNING: Skipping tasteBuilder-remover: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music 
WARNING: Skipping upgrade-button-remover: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music

**Comment by ManorSailor** [comment]
This is normal. The patches you get a warning for clearly mentions that they are only compatible with YT music, hence, they cannot possibly be applied on main YT app. Ignore them, you do not need to worry about anything as long as your app is working fine

**Comment by gosndka** [comment]
> This is normal. The patches you get a warning for clearly mentions that they are only compatible with YT music, hence, they cannot possibly be applied on main YT app. Ignore them, you do not need to worry about anything as long as your app is working fine
Thank you
