### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by ronin08** [n0k0m3/revanced-build-template#36]
It says 'invalid URL' while downloading from uptodown.

**Comment by n0k0m3** [comment]
Can't reproduce can you give me the build log?

**Comment by ronin08** [comment]
![IMG_20220717_214417](https://user-images.githubusercontent.com/75478274/179411030-e5e4a9f9-6b71-48fd-a7a6-8137d791a02f.jpg)
Here's the log. Well I'll try again with fresh template.
Also version 17.27.39 is now compatible, add it.

**Comment by n0k0m3** [comment]
17.27.39 is not on uptodown
