### ISSUE TITLE
Patches List

### ISSUE THREAD

**Issue by KevinNitroG** [n0k0m3/revanced-build-template#38]
Excuse me how about changing Patches List in [List of Available Patches](https://github.com/n0k0m3/revanced-build-template/blob/main/PATCHES_GUIDE.md#list-of-available-patches) to [Revanced's Patches List](https://github.com/revanced/revanced-patches#list-of-available-patches)? It's updated with every new released patches.
Thank you for your consideration.

**Comment by n0k0m3** [comment]
That makes sense, thanks for the suggestion
