### ISSUE TITLE
Explicit include and exclude patches

### ISSUE THREAD

**Issue by n0k0m3** [n0k0m3/revanced-build-template#42]
Revanced patcher now has both including and excluding patches. Some patches are included by default but there are some that needs to be included explicitly.

We need to modify the script to read from `patches.txt` in a way that can do both exclude and include in a same file

**Comment by ManorSailor** [comment]
Hmm. I see. What's the flag to explicitly include patches? Is it `-i`?

**Comment by ManorSailor** [comment]
> I'd assume so, haven't got time to check yet

Its `-i`.  
By far the most challenging thing would be to figure out how to distinguish both types of patches
Anyway. I see 2 ways how this can be implemented. However, both of them have some limitations:

1. Making the user add flag prefixes to the patches they want to exclude/include themselves.
  - Not really reliable. Users might mess up & later complain that script isn't working
  - Easier to implement, minimal changes required in the current setup

2. Dividing the patches file into two separate sections, one where user will enter patches to be `excluded` & other where they will add patches to be `included`
 - It is a bit nuance to enter patches in different sections
 - Not that typical, can be implemented with some efforts.
 
Personally, I think the 2nd method is better. We can make the script read specific parts of a file to obtain excluded & included patches & then it will only be a matter of two conditional statements to decide which patch goes where.

What do you think?

**Comment by n0k0m3** [comment]
Yep I'm thinking of sectioning the `patches.txt`, basically when it reach the 2nd `#` then we'll switch to read includes patches

**Comment by ManorSailor** [comment]
@n0k0m3 Alright. Are you working on it? I'm already working on a separate feature to reduce build times which might conflict with the changes here, I can implement this if it's okay

**Comment by n0k0m3** [comment]
That'd be great as I'll not work on this until weekend

**Comment by ManorSailor** [comment]
> That'd be great as I'll not work on this until weekend

The PR is up ;)
