### ISSUE TITLE
Other download sources

### ISSUE THREAD

**Issue by ramanveerji** [n0k0m3/revanced-build-template#44]
Add other download sources other then uptodown as uptodown has not the updated version of YouTube. Or add something so that we can manually add and upload original YouTube apk then we can run actions to generate revanced apk

**Comment by n0k0m3** [comment]
Regarding alternative sources I already explained it in #14 

The script used to have a build action that fetch from Github Release so I'll probably cherry pick that and make a new action. Will work on that this weekend

**Comment by Chicos123** [comment]
> Regarding alternative sources I already explained it in #14

Try this apkmirror download script. It works perfectly.
https://github.com/j-hc/revanced-magisk-module/blob/main/utils.sh

**Comment by sawankumarbundelkhandi** [comment]
this can be closed now as the script now downloads it from apkmirror
