### ISSUE TITLE
Add twitter patch.

### ISSUE THREAD

**Issue by ronin08** [n0k0m3/revanced-build-template#49]
Revanced patches now include patch for twitter too.

**Comment by missemily2022** [comment]
@ronin08 The Twitter Patch is for Twitter and not for Youtube. So you cannot expect it`s support here.

**Comment by ronin08** [comment]
revanced is not limited to youtube. leave it to the maintainer to decide. don't jump anywhere mindlessly 

> @ronin08 The Twitter Patch is for Twitter and not for Youtube. So you cannot expect it`s support here.

**Comment by missemily2022** [comment]
@ronin08 But the current ReVanced Builder Repo we are communicating at only develops YouTube APKs
It does not do anything else

Moreover it's not upto to you to decide what I can speak and what I cannot!

**Comment by ronin08** [comment]
has it mentioned in the repo, that it'll only patch youtube ? No. right!
then why are you arguing like a kid. You're the one who interrupted in the issue and suggesting me what should I expect. I already told you to leave that decision for the repo maintainer to take.

**Comment by missemily2022** [comment]
@ronin08 You are the one who thinks I am arguing like a kid

**Comment by ronin08** [comment]
good. but check this out https://github.com/XDream8/revanced-creator
builds everything with workflow.

> @ronin08 I modified the script and run successfully on my folk. Feel free to check. https://github.com/quyleanh/revanced-build-template
> 
> Note: Reddit cannot be patched. I have no time to check yet. You can use Infinity for better experience.

**Comment by quyleanh** [comment]
@ronin08 I've already starred, lol. Will check it out.

**Comment by ronin08** [comment]
> @ronin08 I've already starred, lol. Will check it out.

nice nice. by the way it's too easy: run the workflow from the forked repo, and download the apks from the build artifacts! that's it.
