### ISSUE TITLE
fork vs. template

### ISSUE THREAD

**Issue by cyberboh** [n0k0m3/revanced-build-template#5]
I have cloned thsi repo as template, then if there in an update from you, how to update to my repo?
Usually i can update it if i fork the repo
Or can i fork but without contribution? Im new on github and coding

**Comment by n0k0m3** [comment]
Kinda oversight on my part, you can try this solution: https://stackoverflow.com/questions/56577184/github-pull-changes-from-a-template-repository

**Comment by cyberboh** [comment]
That works. :)
