### ISSUE TITLE
Sign with uber-apk-signer

### ISSUE THREAD

**Issue by Chicos123** [n0k0m3/revanced-build-template#50]
![sign](https://user-images.githubusercontent.com/23288869/181422424-41805371-3f2f-45d5-be88-3d1f9bb1ec6f.jpg)

Revanced does not automatically apply verified signatures.
So, how about using _uber-apk-signer_ to temporarily sign the app?
https://github.com/patrickfav/uber-apk-signer

The command is simple.
`java -jar /uber-apk-signer.jar --allowResign --apks /revanced.apk`

**Comment by n0k0m3** [comment]
I'd rather not use a 3rd party signer when revanced-cli already allows using a custom key. I'll implement it soon with debug keystore
