### ISSUE TITLE
Latest Version - Not Available

### ISSUE THREAD

**Issue by missemily2022** [n0k0m3/revanced-build-template#52]
Strangely this time 
A newer version of YouTube has been released officially but not been uploaded in UptoBox to 17.29.34

So I guess it's high time we search for Alternatives though if APKs cannot be fetched automatically via those Alternatives , it wont be very useful to peeps

**Comment by sawankumarbundelkhandi** [comment]
this can be closed now as the script now downloads it from apkmirror
