### ISSUE TITLE
How to keep 'forked'/template-based clone of repo up to date?

### ISSUE THREAD

**Issue by morpheasgr** [n0k0m3/revanced-build-template#61]
I have a question on how this template works.

It seems that once I create a repo off the template, my private project is based on your old codebase and is not considered an fork where I can pull the latest changes from. From what I see in the code, the versions it grabs are based on the versions.json from my cloned copy of your project, not yours. Am I correct?

I tried experimenting with a Github bot called Pull. Sadly my clone is not considered a fork anymore so it cannot pull from your changes. Also does this rely on you manually updating the recommended versions by hand or does this scrape that info via the actions and shell scripts on activation?

**Comment by n0k0m3** [comment]
Sadly you need to use local git for this: https://stackoverflow.com/questions/56577184/github-pull-changes-from-a-template-repository

Or you can make a github bot/action to do the work automatically
