### ISSUE TITLE
Error: Resource not accessible by integration

### ISSUE THREAD

**Issue by c-dev-acc1** [n0k0m3/revanced-build-template#74]
Run marvinpinto/action-automatic-releases@latest
  
Initializing the Automatic Releases action
Determining release tags
Retrieving commit history
  Determining state of the previous release
  Searching for SHA corresponding to previous "tags/latest" release tag
  Could not find SHA corresponding to tag "tags/latest" (Not Found). Assuming this is the first release.
  Retrieving commits between HEAD and 12[17](https://github.com/c-dev-acc1/revanced-build/actions/runs/3913787846/jobs/6690249421#step:7:19)f8393b7e3ef402e00d56f7a4ba5d173eae1a
  Successfully retrieved 0 commits between HEAD and 1217f8393b7e3ef402e00d56f7a4ba5d173eae1a
Generating changelog
Generating release tag
  Attempting to create or update release tag "latest"
  Could not create new tag "refs/tags/latest" (Resource not accessible by integration) therefore updating existing tag "tags/latest"
  Error: Resource not accessible by integration
  (node:2048) UnhandledPromiseRejectionWarning: HttpError: Resource not accessible by integration
      at /home/runner/work/_actions/marvinpinto/action-automatic-releases/latest/dist/index.js:1:361954
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
  (node:2048) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
  (node:2048) [DEP00[18](https://github.com/c-dev-acc1/revanced-build/actions/runs/3913787846/jobs/6690249421#step:7:21)] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by DestroyScript** [comment]
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository

**Comment by DestroyScript** [comment]
![Uploading Screenshot_20230114-174229_Chrome.png…]()

**Comment by DestroyScript** [comment]
![IMG_20230114_174348_204](https://user-images.githubusercontent.com/122464646/212496083-0decb2b9-fc37-4c6b-9827-9af49cba34f3.jpg)
